### ISSUE TITLE
I can't log in

### ISSUE THREAD

**Issue by pitchfrog09** [zxcnoname666/SoundCloud-Desktop#1]
When I try to log in, the login window turns white and nothing happens

**Comment by zxcloli666** [comment]
Hello.
Are you getting an email address entry window?
Can you open the page - https://secure.soundcloud.com in your browser?
What version of the app did you install?

![image](https://github.com/zxcnoname666/SoundCloud-Desktop/assets/156155219/f63933df-a10a-46cf-80a6-1265a207cfa6)

**Comment by zxcloli666** [comment]
If the problem occurs after clicking on the "continue" button, try checking to see if your page is opening - https://geo.captcha-delivery.com/
It should display the error "Invalid API URL", this is the captcha that soundcloud is using

**Comment by pitchfrog09** [comment]
The e-mail input window appears, and when you click on the link, you can see this:
![Screenshot_7](https://github.com/zxcnoname666/SoundCloud-Desktop/assets/77050979/bdc9883b-f2d6-428e-afc3-c0bfcb2dcd0d)
I have installed version 1.6.2
When opening the site https://geo.captcha-delivery.com / it is not possible to access the site as if there is no Internet, perhaps this is due to the fact that in my country SoundCloud only works with a VPN, however, even with or without VPN, when entering email and continuing, a white screen hangs in the login window.
![Screenshot_8](https://github.com/zxcnoname666/SoundCloud-Desktop/assets/77050979/c736f8ce-c323-4fbf-b0bc-43fd142d456e)

**Comment by pitchfrog09** [comment]
I tried using another VPN and it worked, sorry to bother you

**Comment by zxcloli666** [comment]
In version 1.7 I added a check to connect to a captcha without a proxy, and if it is blocked by the ISP, the connection will go through the proxy.
