### ISSUE TITLE
Вы были заблокированы

### ISSUE THREAD

**Issue by BigDoKich** [zxcnoname666/SoundCloud-Desktop#9]
После последнего обновления приложения не получается сделать какие либо действия, по типу добавить музыку в плейлист или убрать ее, сперва просит пройти капчу, а потом вовсе пишет что "вы были заблокированы", ниже полный текст
Вы были заблокированы

Почему эта блокировка? Нечто в поведении браузера нас насторожило.

Есть неколько вариантов:
вы перемещаетесь по страницам и нажимаете на кнопки со сверхчеловеческой скоростью
что-то блокирует работу javascript на вашем компьютере
в той же сети (), что и вы, находится робот

**Comment by zxcloli666** [comment]
Привет.
Внес некоторые корректировки в прокси.
Отпиши, работает ли у тебя.

**Comment by BigDoKich** [comment]
неа(
установил обнову, снова пытаюсь поставить лайк треку кидает на капчу мазайку слева, потом снова тыкаю и сообщение о блокировке, текст тоже самый, ток IPшник в скобочках меняется. Думал что warp конфиг как-то конфликтует, но с ним и без него тоже самое

**Comment by zxcloli666** [comment]
Возможно это из-за того, что api.soundcloud.com проксируется, а geocaptcha нет.
У тебя сайт https://api.soundcloud.com без прокси открывается?

**Comment by BigDoKich** [comment]
а как это проверить, прост не шарю? я приложение открываю и там тыкаю. Если ты имеешь ввиду приложение, то при запуске пишет, что подключен к Main Proxy, Bypass Proxy

**Comment by zxcloli666** [comment]
Попробуй в браузере открыть, если не блокируется - откроется, если блокируется - не откроется

**Comment by BigDoKich** [comment]
в браузере не открывается soundcloud, если включить впн, то все ок

**Comment by zxcloli666** [comment]
а если без впна?
попробуй открыть без впна в браузере:
https://geo.captcha-delivery.com/
https://api.soundcloud.com/
и скажи какие домены открываются, а какие нет

**Comment by BigDoKich** [comment]
блин бро, я наверное чет не понимаю, открываю эти ссылки мне на геокапче кидает
 invalid API
 URL This is not a valid API URL.

Powered By: Datadome API Server
на api soundcloud
{
  "code": 401,
  "message": "",
  "link": "https://developers.soundcloud.com/docs/api/explorer/open-api",
  "status": "401 - Unauthorized",
  "errors": [],
  "error": null
}
c впном и без одно и тоже

**Comment by zxcloli666** [comment]
Если без впна открываются (то, что выдает ошибку - это не важно, главное, чтобы сайт открывался), то они у тебя не блокируются, и трафик должен без прокси проходить
Возможно где-то трафик через проксю на api идет, и он из-за этого капчу не принимает, так как она без прокси, если работает без него

**Comment by BigDoKich** [comment]
И что в таком случае делать? (обновил до последней версии, такая же проблема)

**Comment by zxcloli666** [comment]
Прости за долгий ответ.
Сами ссылки у тебя открываются без впна, значит блокировки у тебя нету, и подключается к soundcloud без прокси.

Я по коду проверил, лайки и изменения плейлистов не проксируются отдельно (как треки для обхода блокировок), поэтому это скорее всего soundcloud что-то ограничивает

**Comment by BigDoKich** [comment]
Как-то странно, вроде бы работало все, потом резко бац и все, получается ждать чуда или имеет смысл им в тп написать не упоминая это приложение?

**Comment by zxcloli666** [comment]
Они там что-то с капчей мутят, у меня иногда какую-то левую выдает раз в пару дней
У себя я решил это знатным таким костылем - открываю трек на колесико мыши в браузере, и добавляю в плейлист, но способ конечно да.

Обходить защиту муторно, так как я обойду, а они снова какие-нибудь изменения в защиту внесут, и прикроют доступ.
Немного потыкаюсь, может натыкаю что-то и заработает на месяц.

**Comment by BigDoKich** [comment]
А, так это не у меня одного, я думал, что это чисто мой локальный баг. Щас тестил плашка что вы забанены появилась даже в браузере, когда пытался под США впном зайти, перешел на ЮК - зашло норм
Ну я сам уже так же прикинул, просто в браузере манипуляции делать, было бы прикольно, если бы также можно было на телефоне сделать, тк их приложение не всегда с впном получается обойти региональные ограничения, из-за чего некоторые треки требуют бабки, либо вообще недоступны

**Comment by zxcloli666** [comment]
С телефонным приложением ограничения больше по лишней инициативе операторов, у меня где-то полгода-год назад оно стало без блокировок работать
В базе РКН только основной домен (`soundcloud.com`), а всякие api* должны работать без блокировок

Я пока в разных браузерах проверял капчу, у меня она жила своей жизнью: могла пройти, могла не пройти, даже в одной сессии в браузере (под инкогнито)
В приложении капча нормально проходит на моменте с авторизацией, а в дев-сборке - не проходит, хоть там ни в js скриптах, ни в заголовках разницы я не заметил.
Если капча размер окна собирает или какой-нибудь фингерпринт, чтобы необычные паттерны выявить, то совсем не здорово получится.

Либо просто капча корявая, и через раз работает, может поэтому soundcloud иногда другие капчи ставят

**Comment by zxcloli666** [comment]
Да, тут скорее проблема в том, что soundcloud неправильно подключили datadome.
Они каждый новый запрос на risky-api создают новую сессию капчи, и перезаписывают куки, из-за чего ты решаешь капчу, а soundcloud тебе новую сессию выдает, и так по кругу. И в итоге datadome банит сеть из-за количества запросов на капчу

**Comment by zxcloli666** [comment]
> Если капча размер окна собирает или какой-нибудь фингерпринт, чтобы необычные паттерны выявить, то совсем не здорово получится.

Там и сбор размера окна, и размера окошка капчи, и фингерпринт видеокарты, и часовой пояс. В общем, целый набор

**Comment by zxcloli666** [comment]
> Они каждый новый запрос на risky-api создают новую сессию капчи

Самый мем в том, что когда ты проходишь капчу, тебе в get запросе выдается cookie, которое надо поставить, чтобы пометить свою сессию как легитимную. И SoundCloud этого не делает, создавая новую сессию
По крайней мере, так у меня

**Comment by BigDoKich** [comment]
Понял, кароч ждем фиксов от них
